# Generated by Django 3.2.9 on 2022-06-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_frontimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontImage',
        ),
    ]
