# Generated by Django 3.2.9 on 2022-06-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_fimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fimage',
        ),
    ]
