# Generated by Django 3.2.9 on 2022-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_firstname_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='box',
            field=models.BooleanField(default=''),
        ),
    ]
