# Generated by Django 3.2.9 on 2022-06-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customer_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='box',
        ),
    ]
